data:
  csv_raw: '../data/raw/bike_rentals.csv'
  csv_cleaned: '../data/clean/bike_rentals_clean.csv'

testsplit:
  random_state: 42
  test_size: 0.2

encoder:
  onehot: '../encoders/onehot.pkl'

scaler:
  standard: '../scalers/standard.pkl'
  minmax: '../scalers/minmax.pkl'
  
model:
  KNN: '../models/knn.pkl'